# Generated by Django 5.2.6 on 2025-09-25 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=35)),
                ('apellido_alumno', models.CharField(max_length=35)),
                ('fecha_nacimiento_alumno', models.DateField(blank=True, null=True)),
                ('genero_alumno', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['apellido_alumno', 'nombre_alumno'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=45)),
                ('descripcion_asignatura', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictadoClase',
            fields=[
                ('dictado_clase', models.AutoField(primary_key=True, serialize=False)),
                ('id_grado', models.IntegerField()),
                ('id_asignatura', models.IntegerField()),
                ('dni_empleado', models.IntegerField()),
            ],
            options={
                'db_table': 'dictados_clases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
                ('asientos_disponibles', models.IntegerField()),
            ],
            options={
                'db_table': 'grados',
                'ordering': ['nombre_grado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'parentescos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=35)),
                ('telefono_tutor', models.CharField(max_length=15, null=True)),
                ('correo_tutor', models.EmailField(max_length=100, unique=True)),
                ('genero_tutor', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'tutores',
                'ordering': ['apellido_tutor', 'nombre_tutor'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXGrado',
            fields=[
                ('id_alumno_x_grado', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.DateTimeField(auto_now_add=True)),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.alumno')),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.grado')),
            ],
            options={
                'db_table': 'alumnos_x_grados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=35)),
                ('apellido_empleado', models.CharField(max_length=35)),
                ('telefono_empleado', models.CharField(max_length=15)),
                ('correo_empleado', models.EmailField(max_length=100, unique=True)),
                ('genero_empleado', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.rol')),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido_empleado', 'nombre_empleado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXTutor',
            fields=[
                ('id_alumno_x_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.alumno')),
                ('id_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.parentesco')),
                ('dni_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.tutor')),
            ],
            options={
                'db_table': 'alumno_x_tutor',
                'managed': True,
            },
        ),
    ]
