# Generated by Django 5.2.6 on 2025-09-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnoxtutor',
            name='dni_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretaria.alumno'),
        ),
        migrations.AlterField(
            model_name='alumnoxtutor',
            name='dni_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.tutor'),
        ),
        migrations.AlterField(
            model_name='alumnoxtutor',
            name='id_parentesco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secretaria.parentesco'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='correo_tutor',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
