# Generated by Django 5.2.6 on 2025-10-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=35)),
                ('apellido_empleado', models.CharField(max_length=35)),
                ('telefono_empleado', models.CharField(blank=True, max_length=15, null=True)),
                ('genero_empleado', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('correo_empleado', models.EmailField(max_length=100, unique=True)),
                ('estado_empleado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=8)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='directores.rol')),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido_empleado', 'nombre_empleado'],
                'managed': True,
            },
        ),
    ]
