# Generated by Django 5.2.6 on 2025-10-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado_empleado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8),
        ),
    ]
