# Generated by Django 5.2.6 on 2025-10-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_asignatura', models.CharField(max_length=45)),
                ('descripcion_asignatura', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asignaturas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DictadoClase',
            fields=[
                ('dictado_clase', models.AutoField(primary_key=True, serialize=False)),
                ('id_grado', models.IntegerField()),
                ('id_asignatura', models.IntegerField()),
                ('dni_empleado', models.IntegerField()),
            ],
            options={
                'db_table': 'dictados_clases',
                'managed': True,
            },
        ),
    ]
