# Generated by Django 5.2.6 on 2025-10-01 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=35)),
                ('apellido_alumno', models.CharField(max_length=35)),
                ('fecha_nacimiento_alumno', models.DateField(blank=True, null=True)),
                ('genero_alumno', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'alumnos',
                'ordering': ['apellido_alumno', 'nombre_alumno'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'parentescos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=35)),
                ('telefono_tutor', models.CharField(max_length=15, null=True)),
                ('correo_tutor', models.EmailField(max_length=100, unique=True)),
                ('genero_tutor', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'tutores',
                'ordering': ['apellido_tutor', 'nombre_tutor'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXTutor',
            fields=[
                ('id_alumno_x_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutor.alumno')),
                ('id_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.parentesco')),
                ('dni_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor')),
            ],
            options={
                'db_table': 'alumno_x_tutor',
                'managed': True,
            },
        ),
    ]
