# Generated by Django 5.2.6 on 2025-09-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('fecha_nacimiento_alumno', models.DateField()),
                ('genero_alumno', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
            ],
            options={
                'ordering': ['apellido_alumno', 'nombre_alumno'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=50)),
                ('telefono_tutor', models.CharField(max_length=20)),
                ('correo_tutor', models.EmailField(max_length=100)),
                ('genero_tutor', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
            ],
            options={
                'ordering': ['apellido_tutor', 'nombre_tutor'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='Secretario.alumno')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretario.parentesco')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='Secretario.tutor')),
            ],
            options={
                'ordering': ['alumno', 'tutor'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('alumno', 'tutor'), name='unique_alumno_tutor')],
            },
        ),
    ]
