# Generated by Django 5.2.6 on 2025-10-01 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id_grado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grado', models.CharField(max_length=50)),
                ('asientos_disponibles', models.IntegerField()),
            ],
            options={
                'db_table': 'grados',
                'ordering': ['nombre_grado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AlumnoXGrado',
            fields=[
                ('id_alumno_x_grado', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.DateTimeField(auto_now_add=True)),
                ('dni_alumno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tutor.alumno')),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='secretario.grado')),
            ],
            options={
                'db_table': 'alumnos_x_grados',
                'managed': True,
            },
        ),
    ]
