# Generated by Django 5.2.6 on 2025-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False, verbose_name='DNI')),
                ('nombre_alumno', models.CharField(max_length=35, verbose_name='Nombre')),
                ('apellido_alumno', models.CharField(max_length=35, verbose_name='Apellido')),
                ('fecha_nacimiento_alumno', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero_alumno', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('observaciones_alumno', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
