# Generated by Django 5.2.6 on 2025-09-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secretario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id_parentesco', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco_nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tutor', models.CharField(max_length=35)),
                ('apellido_tutor', models.CharField(max_length=35)),
                ('telefono_tutor', models.CharField(max_length=15)),
                ('correo_tutor', models.CharField(max_length=100)),
                ('genero_tutor', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_alumno',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='dni_alumno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento_alumno',
            field=models.DateField(default='2015-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='genero_alumno',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_alumno',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='observaciones_alumno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlumnoXTutor',
            fields=[
                ('id_alumno_x_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretario.alumno')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretario.parentesco')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Secretario.tutor')),
            ],
        ),
    ]
